GLOBAL:
  LOG_LEVEL: 2
  GPU_INDICES:
  - 0
  RANDOM_SEED: 0
  ANOMALY_DETECTION: false
  FILTER_WARNINGS: true
  METHOD_TYPE: FasterGS
  DATASET_TYPE: RefNeRFSynthetic
MODEL:
  SH_DEGREE: 3
  PPISP:
    USE: false
    CONTROLLER_TRAINING_STEPS: 5000
    CONTROLLER_DISTILLATION: true
  DEFERRED_REFLECTION:
    USE: true
    REFL_INIT_VALUE: 0.001
    ENVMAP_RESOLUTION: 128
RENDERER:
  SCALE_MODIFIER: 1.0
  PROPER_ANTIALIASING: false
  FORCE_OPTIMIZED_INFERENCE: false
TRAINING:
  LOAD_CHECKPOINT: null
  MODEL_NAME: fastergs_dr_toaster
  NUM_ITERATIONS: 85001
  RUN_VALIDATION: false
  DATA:
    PRELOADING_LEVEL: 2
    FIELDS:
    - rgb
    PRECOMPUTE_RAYS: false
    RAYS_TO_DEVICE: false
  BACKUP:
    FINAL_CHECKPOINT: true
    RENDER_TESTSET: true
    RENDER_TRAINSET: false
    RENDER_VALSET: false
    INTERMEDIATE_RENDERINGS: true
    VISUALIZE_ERRORS: false
    INTERVAL: -1
    TRAINING_STATE: false
  TIMING:
    ACTIVATE: true
    INCLUDE_DATALOADING_IN_TOTAL: false
    INCLUDE_PRETRAINING_IN_TOTAL: false
    INCLUDE_POSTTRAINING_IN_TOTAL: false
  WANDB:
    ACTIVATE: false
    ENTITY: null
    PROJECT: faster_gs
    LOG_IMAGES: true
    INDEX_VALIDATION: -1
    INDEX_TRAINING: -1
    INTERVAL: 500
    SWEEP_MODE:
      ACTIVE: false
      START_ITERATION: 999
      ITERATION_STRIDE: 1000
      NUM_IMAGES: -1
  WRITE_VRAM_STATS: true
  GUI:
    ACTIVATE: false
    RENDER_INTERVAL: 10
    GUI_STATUS_ENABLED: true
    GUI_STATUS_INTERVAL: 20
    SKIP_GUI_SETUP: false
    FPS_ROLLING_AVERAGE_SIZE: 100
  DENSIFICATION_START_ITERATION: 500
  DENSIFICATION_END_ITERATION: 32000
  DENSIFICATION_INTERVAL: 100
  DENSIFICATION_GRAD_THRESHOLD: 0.0002
  DENSIFICATION_PERCENT_DENSE: 0.01
  SPEEDYSPLAT_PRUNING:
    USE: false
    START_ITERATION: 6000
    END_ITERATION: 61000
    INTERVAL: 3000
    SOFT_PRUNING_RATIO: 0.8
    HARD_PRUNING_RATIO: 0.3
  USE_MCMC: false
  MAX_PRIMITIVES: 1000000
  OPACITY_RESET_INTERVAL: 3000
  EXTRA_OPACITY_RESET_ITERATION: 500
  MORTON_ORDERING_INTERVAL: 5000
  MORTON_ORDERING_END_ITERATION: 32000
  FILTER_3D:
    USE: false
    ORIGINAL_FORMULATION: false
    FILTER_VARIANCE: 0.2
  USE_RANDOM_BACKGROUND_COLOR: false
  RANDOM_BACKGROUND_IF_ALPHA_OR_MASK: false
  WHITE_BACKGROUND: true
  MIN_OPACITY_AFTER_TRAINING: 0.00392156862745098
  RANDOM_INITIALIZATION:
    FORCE: false
    N_POINTS: 100000
    ENABLE_CARVING: true
    CARVING_IN_ALL_FRUSTUMS: false
    CARVING_ENFORCE_ALPHA: false
  LOSS:
    LAMBDA_L1: 0.8
    LAMBDA_DSSIM: 0.2
    LAMBDA_OPACITY_REGULARIZATION: 0.0
    LAMBDA_SCALE_REGULARIZATION: 0.0
  OPTIMIZER:
    LEARNING_RATE_MEANS_INIT: 0.00016
    LEARNING_RATE_MEANS_FINAL: 1.6e-06
    LEARNING_RATE_MEANS_MAX_STEPS: 8000
    LEARNING_RATE_SH_COEFFICIENTS_0: 0.0025
    LEARNING_RATE_SH_COEFFICIENTS_REST: 0.000125
    LEARNING_RATE_OPACITIES: 0.05
    LEARNING_RATE_SCALES: 0.005
    LEARNING_RATE_ROTATIONS: 0.001
    LEARNING_RATE_REFLECTION_STRENGTH: 0.006
  DEFERRED_REFLECTION_SCHEDULE:
    INIT_UNTIL_ITERATION: 3000
    PROPAGATION_INTERVAL: 1000
    PROPAGATION_END_ITERATION: 8000
    LONGER_PROPAGATION_ITERATIONS: 24000
    PROPAGATION_ENLARGE_SCALE: 1.5
    PROPAGATION_MIN_OPACITY: 0.9
    PROPAGATION_OPACITY_FLOOR: 0.01
    PROPAGATION_MIN_REFLECTION: 0.001
    SCALE_ENLARGE_THRESHOLD: 0.02
    COLOR_SABOTAGE_THRESHOLD: 0.05
    REFLECTION_THRESHOLD: 0.1
    COLOR_SABOTAGE_NOISE: 0.4
    SPECULAR_TERMINATION_PATIENCE: 0
    OPAC_LR0_INTERVAL: 200
    ENVMAP_LEARNING_RATE: 0.05
    DENSIFICATION_INTERVAL_DURING_PROPAGATION: 500
    PARITY_DIFFUSE_BOOTSTRAP: true
    USE_ENV_SCOPE: false
    ENV_SCOPE_CENTER:
    - 0.0
    - 0.0
    - 0.0
    ENV_SCOPE_RADIUS: 0.0
    REFL_MASK_LOSS_WEIGHT: 0.4
DATASET:
  PATH: /home/alex/Simulon/dev/3DGS-DR/data/toaster
  IMAGE_SCALE_FACTOR: 1
  NORMALIZE_CUBE: null
  NORMALIZE_RECENTER: false
  BACKGROUND_COLOR:
  - 1.0
  - 1.0
  - 1.0
  WHITE_BACKGROUND: true
  NEAR_PLANE: 0.2
  FAR_PLANE: 10000.0
  APPLY_PCA: false
  APPLY_PCA_RESCALE: false
  WHITE_BACKGROUND_EVAL: true
  POINT_CLOUD_FILE: points3d.ply
